-- require "Foraging/forageDefinitions";

-- forageSystem.forageSkillDefinitions = {
-- 	fklr = {
--         name                    = CharacterProfession.FKLR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0.7,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Trash"]               = 10,
-- 			["Junk"]                = 10,
-- 		},
-- 	},
-- 	klbr = {
--         name                    = CharacterProfession.KLBR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 1.75,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Trash"]               = 20,
-- 			["Junk"]                = 20,
-- 		},
-- 	},
-- 	lstr = {
--         name                    = CharacterProfession.LSTR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Firewood"]            = 30,
-- 			["JunkWeapons"]         = 10,
-- 			["Junk"]                = 10,
-- 		},
-- 	},
-- 	adlr = {
--         name                    = CharacterProfession.ADLR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Trash"]               = 10,
-- 			["Junk"]                = 10,
-- 		},
-- 	},
-- 	stcr = {
--         name                    = CharacterProfession.STCR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0.5,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Trash"]               = 10,
-- 			["Junk"]                = 10,
-- 			["JunkWeapons"]         = 10,
-- 		},
-- 	},
-- 	star = {
--         name                    = CharacterProfession.STAR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0.4,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Trash"]               = 10,
-- 			["Junk"]                = 10,
-- 			["JunkWeapons"]         = 10,
-- 			["Ammunition"]          = 30,
-- 		},
-- 	},
-- 	eulr = {
--         name                    = CharacterProfession.EULR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Berries"]             = 5,
-- 			["Mushrooms"]           = 10,
-- 			["Medical"]             = 5,
-- 			["MedicinalPlants"]     = 5,
-- 			["Firewood"]            = 10,
-- 			["Junk"]                = 10,
-- 			["JunkFood"]            = 10,
-- 		},
-- 	},
-- 	mnhr = {
--         name                    = CharacterProfession.MNHR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = -0.5,
-- 		weatherEffect           = 20,
-- 		darknessEffect          = 0,
-- 		specialisations         = {
-- 			["Stones"]				= 30,
-- 			["Trash"]               = 10,
-- 			["JunkWeapons"]         = 5,
-- 			["Junk"]                = 20,
-- 		},
-- 	},
-- 	arar = {
--         name                    = CharacterProfession.ARAR:getName(),
-- 		type                    = "occupation",
-- 		visionBonus             = 0,
-- 		weatherEffect           = 0,
-- 		darknessEffect          = 10,
-- 		specialisations         = {
-- 			["Trash"]               = 33,
-- 			["Junk"]                = 33,
-- 		},
-- 	},
-- };
