BagsAndContainers = BagsAndContainers or {}

BagsAndContainers.Bag_Police = {
	rolls = 2,
	items = {
		"223Box", 10,
		"308Box", 10,
		"44Clip", 8,
		"45Clip", 8,
        "10mmClip", 8,
		"9mmClip", 8,
        "8mmClip", 8,
		"AmmoStraps", 6,
		"AssaultRifle2", 2,
		"Bullets38Box", 10,
		"Bullets44Box", 10,
        "Bullets8Box", 10,
        "Bullets12Box", 10,
        "Bullets10Box", 10,
        "Bullets16Box", 5,
        "Bullets185Box", 8,
		"Bullets45Box", 10,
		"Bullets9mmBox", 10,
		"ChokeTubeFull", 6,
		"ChokeTubeImproved", 6,
		"Crowbar", 8,
		"FirstAidKit", 4,
		"Glasses_Shooting", 8,
		"Gloves_FingerlessGloves", 8,
		"HuntingRifle", 4,
		"HolsterAnkle", 1,
		"HolsterShoulder", 2,
		"HolsterSimple_Black", 8,
		"KnifePocket", 4,
		"M14Clip", 8,
		"Nightstick", 8,
		"Pistol", 8,
		"Pistol2", 6,
        "Type-75", 5,
		"Pistol3", 4,
		"RecoilPad", 6,
		"RedDot", 6,
		"Revolver", 6,
        "EU-K508S", 4,
		"Revolver_Long", 4,
		"Revolver_Short", 8,
		"Shotgun", 10,
        "EIN-12", 10,
        "Type-84", 8,
		"ShotgunSawnoff", 10,
		"ShotgunShellsBox", 10,
		"VarmintRifle", 8,
		"Vest_BulletPolice", 2,
		"x2Scope", 8,
		"x4Scope", 6,
		"x8Scope", 4,
	},
	junk = {
		rolls = 1,
		items = {
			
		}
	},
}